In [1]:
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd
import ast

In [2]:
main_request = requests.get("https://en.wikipedia.org/wiki/Political_party_strength_in_U.S._states")
main_page = BeautifulSoup(main_request.text)

In [5]:
states = main_page.select('.wikitable.sortable tr')[1:]

In [6]:
state_names = []
house_blue_perc = []

In [7]:
for state in states:
    rows = state.select('td')
    state_name = rows[0].text.replace("\n", "")
    
    if state_name == 'Nebraska':
        continue
    
    state_names.append(state_name)
    
    party_in_power, party_ratio = rows[3].text.replace("\n", "").split(' ')
    
    party_numbers = list(map(lambda x: int(''.join(list(filter(str.isdigit, x)))), party_ratio.split('â€“')))
    
    if party_in_power == 'Republican':
        house_blue_perc.append(round(party_numbers[1]/sum(party_numbers)*100, 2))
    else:
        house_blue_perc.append(round(party_numbers[0]/sum(party_numbers)*100, 2))

In [8]:
df = pd.DataFrame({
    'state': state_names,
    'state_house_blue_perc': house_blue_perc
})

In [9]:
df

             state  state_house_blue_perc
0          Alabama                  22.86
1           Alaska                  35.00
2          Arizona                  43.33
3         Arkansas                  25.71
4       California                  72.50
5         Colorado                  54.29
6      Connecticut                  61.11
7         Delaware                  57.14
8          Florida                  42.50
9          Georgia                  37.50
10          Hawaii                  96.00
11           Idaho                  20.00
12        Illinois                  67.80
13         Indiana                  20.00
14            Iowa                  36.00
15          Kansas                  27.50
16        Kentucky                  23.68
17       Louisiana                  30.77
18           Maine                  60.00
19        Maryland                  68.09
20   Massachusetts                  85.00
21        Michigan                  42.11
22       Minnesota                  47.76
23     Mississippi                  30.77
24        Missouri                  29.41
25         Montana                  40.00
26          Nevada                  61.90
27   New Hampshire                  58.33
28      New Jersey                  62.50
29      New Mexico                  61.90
30        New York                  63.49
31  North Carolina                  42.00
32    North Dakota                  21.28
33            Ohio                  27.27
34        Oklahoma                  18.75
35          Oregon                  60.00
36    Pennsylvania                  44.00
37    Rhode Island                  86.84
38  South Carolina                  41.30
39    South Dakota                  14.29
40       Tennessee                  15.15
41           Texas                  38.71
42            Utah                  20.69
43         Vermont                  73.33
44        Virginia                  52.50
45      Washington                  59.18
46   West Virginia                  41.18
47       Wisconsin                  42.42
48         Wyoming                  10.00

In [10]:
df.to_csv('./relevant_data/state_party_line.csv', index=False)